version: 2.1

orbs:
  codacy: codacy/base@2.2.1
  codacy_plugins_test: codacy/plugins-test@0.8.1

jobs:
  unit_test:
    docker:
      - image: circleci/golang:1.13
    working_directory: ~/workdir
    steps:
      - attach_workspace: 
          at: ~/workdir
      - run:
          name: Run go test
          command: go test

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - unit_test:
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: publish_docker_local
          cmd: |
            make docker
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - unit_test
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
